var righ = [
"https://i.imgur.com/P1MIF8e.jpg",
"https://i.imgur.com/tm337UD.jpg",
"https://i.imgur.com/qtKFrmn.jpg",
"https://i.imgur.com/xrq42Pw.jpg",
"https://i.imgur.com/ZgfB0HG.jpg",
"https://i.imgur.com/LH9Uk18.jpg",
"https://i.imgur.com/9p9N0x7.jpg",
"https://i.imgur.com/rJmRvlf.jpg",
"https://i.imgur.com/XU1axIF.gif",
"https://i.imgur.com/TK01aym.gif",
"https://i.imgur.com/O2xZ3Wz.jpg",
"https://i.imgur.com/R2G8Pgt.jpg",
"https://i.imgur.com/NnEca6a.jpg",
"https://i.imgur.com/PggX7Z8.jpg",
"https://i.imgur.com/i4zsfSp.jpg",
"https://i.imgur.com/PWKrdnQ.jpg",
"https://i.imgur.com/PzLTOEf.jpg",
"https://i.imgur.com/IkJkFdi.jpg",
"https://i.imgur.com/IgAnRD1.jpg",
"https://i.imgur.com/LUDV1Fd.jpg",
"https://i.imgur.com/4izS6Ba.jpg",
"https://i.imgur.com/ZKAax2q.jpg",
"https://i.imgur.com/kFg7pJ8.jpg",
"https://i.imgur.com/sGdDUVw.jpg",
"https://i.imgur.com/lYS45kr.jpg",
"https://i.imgur.com/3BKRtze.jpg",
"https://i.imgur.com/bpm9CsW.jpg",
"https://i.imgur.com/2buaZRM.png",
"https://i.imgur.com/wBY8eZw.jpg",
"https://i.imgur.com/gL7OUH7.jpg",
"https://i.imgur.com/cVbqQTk.jpg",
"https://i.imgur.com/Jj6gCYr.png",
"https://i.imgur.com/o85GAdL.jpg",
"https://i.imgur.com/Dm3I2VZ.jpg",
"https://i.imgur.com/ghZCNmm.jpg",
"https://i.imgur.com/jBM78C3.jpg",
"https://i.imgur.com/i7AK3Ag.jpg",
"https://i.imgur.com/0755BmJ.jpg",
"https://i.imgur.com/HlHU475.jpg",
"https://i.imgur.com/gGZitgQ.jpg",
"https://i.imgur.com/osXERLA.jpg",
"https://i.imgur.com/3TNPnPX.jpg",
"https://i.imgur.com/iF2IPbR.jpg",
"https://i.imgur.com/dnqiiDU.jpg",
"https://i.imgur.com/q9TZg3A.jpg",
"https://i.imgur.com/D8eg5bJ.jpg",
"https://i.imgur.com/2xpKgHu.jpg",
"https://i.imgur.com/rWo3u4O.jpg",
"https://i.imgur.com/J0WERp7.jpg",
"https://i.imgur.com/1NjATxK.jpg"
]

module.exports = function() {
  return righ[Math.floor(Math.random() * righ.length)]
}

module.exports.righ = righ